>>> f=open("nonexistent_dir/c19c1322a38085fc0ae2ea60a87c1429","w")
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
IOError: [Errno 2] No such file or directory: 'nonexistent_dir/c19c1322a38085fc0ae2ea60a87c1429'

